name: appkel_for_courier_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+20

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  

  go_router: ^12.1.3
  connectivity_plus: ^6.0.3
  smooth_page_indicator: ^1.1.0
  web_socket_channel: ^2.4.5
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  tf_dio_cache: ^1.0.2
  mask_text_input_formatter: ^2.9.0
  # state management
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.2.0
  # riverpod_annotation:

  # json
  freezed_annotation: ^2.1.0
  pinput: ^3.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.3 
  collection: ^1.18.0
  flutter_cached_pdfview: ^0.4.2
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^16.3.3
  firebase_messaging: ^14.7.19
  android_id: ^0.3.6
  device_info_plus: ^9.1.2
  riverpod_annotation: ^2.3.3
  logging: ^1.2.0
  photo_view: ^0.14.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  image_picker: ^1.0.5
  # permission_handler: ^11.2.0
  pin_code_fields: ^8.0.1
  image_cropper: ^5.0.1
  smooth_star_rating_null_safety: ^1.0.4+2
  url_launcher: ^6.2.3
  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  carousel_slider: ^5.0.0
  # flutter_facebook_auth: ^6.0.4
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  another_flushbar: ^1.12.30
  firebase_crashlytics: ^3.4.20
  firebase_analytics: ^10.9.0
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  uuid: ^4.4.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  # pdf_render: ^1.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  riverpod_generator: ^2.3.9  
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"


flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/map_theme/
    - assets/pdf/




fonts:
  - family: Helvetica
    fonts:
      - asset: assets/fonts/helvetica-light-587ebe5a59211.ttf
        weight: 300
      - asset: assets/fonts/Helvetica.ttf
        weight: 400
      - asset: assets/fonts/Helvetica-Oblique.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Helvetica-Bold.ttf
        weight: 700
      - asset: assets/fonts/Helvetica-BoldOblique.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/helvetica-rounded-bold-5871d05ead8de.otf
        weight: 800
      - asset: assets/fonts/helvetica-rounded-bold-900.otf
        weight: 900


      #helvetica-compressed-5871d14b6903a.otf
