// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5tiv4sYG3VR0fbBggs_4fTpp88cRVC8',
    appId: '1:167425101513:web:b1c941fbf0cf0309bcc718',
    messagingSenderId: '167425101513',
    projectId: 'appkel-f1140',
    authDomain: 'appkel-f1140.firebaseapp.com',
    storageBucket: 'appkel-f1140.appspot.com',
    measurementId: 'G-3FKNM99Y7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzqezyCbFdqNko55TAp1fcMdduuwbV7E',
    appId: '1:167425101513:android:7840e3e0221f55a6bcc718',
    messagingSenderId: '167425101513',
    projectId: 'appkel-f1140',
    storageBucket: 'appkel-f1140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBru1VrSLKkEvbvoU9z0gh6bOuHGXGMgAg',
    appId: '1:167425101513:ios:ecf53483068297ffbcc718',
    messagingSenderId: '167425101513',
    projectId: 'appkel-f1140',
    storageBucket: 'appkel-f1140.appspot.com',
    androidClientId:
        '167425101513-3qikr61tiu8jfk225dr7jirhorkv6rhl.apps.googleusercontent.com',
    iosClientId:
        '167425101513-btugbqevua412ou3q1hq3jug4mq218j1.apps.googleusercontent.com',
    iosBundleId: 'dev.courier.appkelkg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBru1VrSLKkEvbvoU9z0gh6bOuHGXGMgAg',
    appId: '1:167425101513:ios:e5f6f281042abfdebcc718',
    messagingSenderId: '167425101513',
    projectId: 'appkel-f1140',
    storageBucket: 'appkel-f1140.appspot.com',
    androidClientId:
        '167425101513-3qikr61tiu8jfk225dr7jirhorkv6rhl.apps.googleusercontent.com',
    iosClientId:
        '167425101513-8hfm7jitbpkf92crm7bvauandb1epp7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appkelFlutter.RunnerTests',
  );
}
